### ISSUE TITLE
Too many stats are cast to floats

### ISSUE THREAD

**Issue by ira-bv** [michael-doubez/filestat_exporter#9]
crc32, unix time and other metrics should stay int so they can be compared, instead the output coes out as float. size in megabytes instead of bytes is less of an issue, but it would be nice to have it consistent.

**Comment by michael-doubez** [comment]
Gauge are exposed as float in prometheus ([see code](https://sgithub.fr.world.socgen/RTMA/lseg_gtp_feed/blob/3b692c112deebd0d9c89768d86078b3f9bed2451/src/GTP_RTDN_Feeder.cpp#L44)).

I agree with you, I would have preferred a nice int representation.

Note that for crc32, I don't much care because the information wanted is that the file content changed.
